---
title: "git_00"
author: "Diana Reyes"
date: "September 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

Twinkle, Twinkle Little Bat


How I wonder what you're at!


Up above the world you fly,


Like a tea tray in the sky.


Twinkle, twinkle, little bat!


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

You can’t because you don’t know how to speak.


If you had any feelings, you that dug



With your own hand—how could you?—his little grave;



I saw you from that very window there,



Making the gravel leap in air


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,

Shining with all his might:

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Bottomless vales and boundless floods,
         
         
And chasms, and caves, and Titan woods,
         
         
With forms that no man can discover
         
         
For the tears that drip all over;
           
           
Mountains toppling evermore
            
            
Into seas without a shore;
           
           
Seas that restlessly aspire,


Surging, unto skies of fire;


Lakes that endlessly outspread
            
            
Their lone waters- lone and dead,-


Their still waters- still and chilly
            
            
With the snows of the lolling lily.

